# Generated by Django 4.2 on 2023-04-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comics/'),
        ),
    ]
