# Generated by Django 4.2 on 2023-05-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='is_hero',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='species',
            field=models.CharField(choices=[('H', 'human'), ('D', 'dios'), ('M', 'mutant'), ('U', 'unknown')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
